server {
    listen ${GATEWAY_CONTAINER_PORT};

    location /api/auth/ {
        proxy_pass http://auth-service:${AUTH_PORT}/auth/;
    }

    location /api/ {
        proxy_pass http://backend:${BACKEND_PORT}/;
    }

    location / {
        proxy_pass http://frontend:${FRONTEND_PORT};
    }
}