apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: carlog
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: carlog-backend:1.0
          imagePullPolicy: IfNotPresent
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - configMapRef:
                name: carlog-config
            - secretRef:
                name: carlog-secrets